// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['core']['Bind']['AppInfo']();
}

export function Config() {
  return window['go']['core']['Bind']['Config']();
}

export function ResetApp() {
  return window['go']['core']['Bind']['ResetApp']();
}
