// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APISession() {
  return window['go']['app']['Bind']['APISession']();
}

export function AppInfo() {
  return window['go']['app']['Bind']['AppInfo']();
}

export function Config() {
  return window['go']['app']['Bind']['Config']();
}

export function LogFrontendError(arg1) {
  return window['go']['app']['Bind']['LogFrontendError'](arg1);
}

export function OpenLogDirectory() {
  return window['go']['app']['Bind']['OpenLogDirectory']();
}

export function PrepareReset(arg1) {
  return window['go']['app']['Bind']['PrepareReset'](arg1);
}

export function ResetApp() {
  return window['go']['app']['Bind']['ResetApp']();
}
