// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {httpapi} from '../models';

export function APISession():Promise<httpapi.ResponseData>;

export function AppInfo():Promise<httpapi.ResponseData>;

export function Config():Promise<httpapi.ResponseData>;

export function LogFrontendError(arg1:string):Promise<void>;

export function OpenLogDirectory():Promise<void>;

export function PrepareReset(arg1:string):Promise<void>;

export function ResetApp():Promise<void>;
