export const packageDownloadDirectory = 'idm_downloads'

export const buildPackageRunBat = (): string => [
  '@echo off',
  'set "SCRIPT_DIR=%~dp0"',
  'powershell -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT_DIR%decrypt.ps1" -TaskFile "%SCRIPT_DIR%idm_tasks.json"',
  'echo.',
  'pause',
].join('\r\n')

// 项目级下载包运行器：未来其他批量导出功能也统一复用这套“等待-验证-收尾”策略。
export const buildPackagePowerShell = (): string => [
  'param([string]$TaskFile)',
  '$ErrorActionPreference = "Stop"',
  '$baseDir = Split-Path -Parent $TaskFile',
  '$logDir = Join-Path $baseDir "logs"',
  'New-Item -ItemType Directory -Force -Path $logDir | Out-Null',
  '$logFile = Join-Path $logDir ("run-" + (Get-Date -Format "yyyyMMdd-HHmmss") + ".log")',
  '$script:MissingFiles = 0',
  '$script:FailedTasks = New-Object System.Collections.Generic.List[string]',
  '$script:FailedTaskKeys = @{}',
  '$script:RecoveryAttempts = @{}',
  '$maxRecoveryAttempts = 3',
  '$maxIdleRounds = 3',
  'function Log([string]$message) {',
  '  $line = "[" + (Get-Date -Format "HH:mm:ss") + "] " + $message',
  '  Write-Host $line',
  '  Add-Content -LiteralPath $logFile -Value $line -Encoding UTF8',
  '}',
  'function FullPath([string]$relativePath) {',
  '  if ([string]::IsNullOrWhiteSpace($relativePath) -or $relativePath -eq ".") { return $baseDir }',
  '  return Join-Path $baseDir $relativePath',
  '}',
  'function TaskLabel($task, [int]$index, [int]$total) {',
  '  $label = if ([string]::IsNullOrWhiteSpace($task.label)) { $task.filename } else { $task.label }',
  '  if ($index -gt 0 -and $total -gt 0) {',
  '    return "[" + $index + "/" + $total + "] " + $label',
  '  }',
  '  return $label',
  '}',
  'function FormatTaskList($tasks, [int]$limit) {',
  '  $items = New-Object System.Collections.Generic.List[object]',
  '  foreach ($item in $tasks) {',
  '    $items.Add($item) | Out-Null',
  '  }',
  '  if ($items.Count -eq 0) { return "none" }',
  '  $max = [Math]::Min($items.Count, $limit)',
  '  $parts = New-Object System.Collections.Generic.List[string]',
  '  for ($i = 0; $i -lt $max; $i++) {',
  '    $task = $items[$i]',
  '    $parts.Add((TaskLabel $task ($i + 1) $items.Count)) | Out-Null',
  '  }',
  '  if ($items.Count -gt $limit) {',
  '    $parts.Add("(+" + ($items.Count - $limit) + " more)") | Out-Null',
  '  }',
  '  return ($parts -join " | ")',
  '}',
  'function TaskKey($task) {',
  '  if ($null -ne $task.taskId -and -not [string]::IsNullOrWhiteSpace($task.taskId)) { return [string]$task.taskId }',
  '  if ($null -ne $task.originalUrl -and -not [string]::IsNullOrWhiteSpace($task.originalUrl)) { return [string]$task.originalUrl }',
  '  return [string]$task.filename',
  '}',
  'function Mark-Failed($task, [string]$reason) {',
  '  $key = TaskKey $task',
  '  if (!$script:FailedTaskKeys.ContainsKey($key)) {',
  '    $script:FailedTaskKeys[$key] = $true',
  '    $script:FailedTasks.Add((TaskLabel $task 0 0) + " :: " + $reason) | Out-Null',
  '  }',
  '  Log ("failed: " + (TaskLabel $task 0 0) + " :: " + $reason)',
  '}',
  'function Is-FailedTask($task) {',
  '  return $script:FailedTaskKeys.ContainsKey((TaskKey $task))',
  '}',
  'function DownloadPath($task) {',
  '  $dir = FullPath $task.downloadDirectory',
  '  $downloadName = if ([string]::IsNullOrWhiteSpace($task.tempFilename)) { $task.filename } else { $task.tempFilename }',
  '  return Join-Path $dir $downloadName',
  '}',
  'function TargetPath($task) {',
  '  $dir = FullPath $task.directory',
  '  return Join-Path $dir $task.filename',
  '}',
  'function Test-StableFile([string]$file) {',
  '  if (!(Test-Path -LiteralPath $file)) { return $false }',
  '  $first = (Get-Item -LiteralPath $file).Length',
  '  Start-Sleep -Milliseconds 200',
  '  if (!(Test-Path -LiteralPath $file)) { return $false }',
  '  $second = (Get-Item -LiteralPath $file).Length',
  '  return ($first -gt 0 -and $first -eq $second)',
  '}',
  'function Unique-Strings($items) {',
  '  $seen = @{}',
  '  $result = New-Object System.Collections.Generic.List[string]',
  '  foreach ($item in @($items)) {',
  '    if (![string]::IsNullOrWhiteSpace($item) -and !$seen.ContainsKey($item)) {',
  '      $seen[$item] = $true',
  '      $result.Add([string]$item) | Out-Null',
  '    }',
  '  }',
  '  return @($result)',
  '}',
  'function Get-DirectHeaders([string]$url) {',
  '  $headers = @{',
  '    "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"',
  '    "Accept" = "image/avif,image/webp,image/apng,image/svg+xml,image/*,audio/*,video/*,*/*;q=0.8"',
  '  }',
  '  try {',
  '    $uri = [Uri]$url',
  '    if ($uri.Scheme -and $uri.Host) {',
  '      $headers["Referer"] = $uri.Scheme + "://" + $uri.Host + "/"',
  '    }',
  '  } catch {',
  '  }',
  '  return $headers',
  '}',
  'function Download-DirectFile([string]$url, [string]$targetFile, [string]$label) {',
  '  $targetDir = Split-Path -Parent $targetFile',
  '  New-Item -ItemType Directory -Force -Path $targetDir | Out-Null',
  '  if (Test-StableFile $targetFile) {',
  '    Log ("skip existing direct file: " + $targetFile)',
  '    return $true',
  '  }',
  '  $tempFile = $targetFile + ".part"',
  '  for ($attempt = 1; $attempt -le 4; $attempt++) {',
  '    try {',
  '      if (Test-Path -LiteralPath $tempFile) { Remove-Item -LiteralPath $tempFile -Force }',
  '      $headers = Get-DirectHeaders $url',
  '      Invoke-WebRequest -Uri $url -Headers $headers -OutFile $tempFile -TimeoutSec 300 -UseBasicParsing',
  '      if (Test-StableFile $tempFile) {',
  '        Move-Item -LiteralPath $tempFile -Destination $targetFile -Force',
  '        Log ("direct completed: " + $targetFile)',
  '        return $true',
  '      }',
  '      Log ("direct unstable file: " + $label)',
  '    } catch {',
  '      Log ("direct download failed attempt " + $attempt + " for " + $label + ": " + $_.Exception.Message)',
  '    }',
  '    Start-Sleep -Seconds (2 * $attempt)',
  '  }',
  '  return $false',
  '}',
  'function Write-ImageSetMetadata($set) {',
  '  $setDir = FullPath $set.folder',
  '  $imgDir = Join-Path $setDir "images"',
  '  $metaPath = Join-Path $baseDir $set.metadataPath',
  '  New-Item -ItemType Directory -Force -Path $imgDir | Out-Null',
  '  $metadata = $set.metadata',
  '  if ($null -ne $metadata.images) {',
  '    foreach ($image in @($metadata.images)) {',
  '      $filePath = Join-Path $imgDir $image.file_name',
  '      if (Test-Path -LiteralPath $filePath) {',
  '        $image.size = [double](Get-Item -LiteralPath $filePath).Length',
  '      }',
  '    }',
  '  }',
  '  if ($null -ne $metadata.audio) {',
  '    $audioName = if ([string]::IsNullOrWhiteSpace($metadata.audio.file_name)) { $set.audio.fileName } else { $metadata.audio.file_name }',
  '    $audioDir = Join-Path $setDir "audio"',
  '    $audioPath = Join-Path $audioDir $audioName',
  '    if (Test-Path -LiteralPath $audioPath) {',
  '      $metadata.audio.file_name = $audioName',
  '      $metadata.audio.path = "audio/" + $audioName',
  '      $metadata.audio.size = [double](Get-Item -LiteralPath $audioPath).Length',
  '    }',
  '  }',
  '  $metadata.audio_status = Get-ImageSetAudioStatus $set',
  '  $metadata.image_count = @($set.images).Count',
  '  $metadata.cover = if (@($set.images).Count -gt 0) { "images/" + (@($set.images)[0].filename) } else { "" }',
  '  $metaJson = $metadata | ConvertTo-Json -Depth 10',
  '  [IO.File]::WriteAllText($metaPath, $metaJson, [System.Text.UTF8Encoding]::new($false))',
  '}',
  'function Download-ImageSets($imageSets) {',
  '  foreach ($set in @($imageSets)) {',
  '    $setDir = FullPath $set.folder',
  '    $imgDir = Join-Path $setDir "images"',
  '    New-Item -ItemType Directory -Force -Path $imgDir | Out-Null',
  '    foreach ($image in @($set.images)) {',
  '      $targetFile = Join-Path $imgDir $image.filename',
  '      if (!(Download-DirectFile $image.url $targetFile ($set.folder + "\\" + $image.filename))) {',
  '        $script:MissingFiles++',
  '      }',
  '    }',
  '    if ($null -ne $set.audio -and -not [string]::IsNullOrWhiteSpace($set.audio.url)) {',
  '      $audioDir = Join-Path $setDir "audio"',
  '      New-Item -ItemType Directory -Force -Path $audioDir | Out-Null',
  '      $audioFile = if ([string]::IsNullOrWhiteSpace($set.audio.fileName)) { "bgm.m4a" } else { $set.audio.fileName }',
  '      if (!(Download-DirectFile $set.audio.url (Join-Path $audioDir $audioFile) ($set.folder + "\\audio\\" + $audioFile))) {',
  '        $script:MissingFiles++',
  '      }',
  '    }',
  '    Write-ImageSetMetadata $set',
  '  }',
  '}',
  'function Get-ImageSetAudioStatus($set) {',
  '  if ($null -ne $set.audio -and -not [string]::IsNullOrWhiteSpace($set.audio.url)) {',
  '    if (Test-Path -LiteralPath (Join-Path (FullPath $set.folder) ("audio\\" + $set.audio.fileName))) {',
  '      return "downloaded"',
  '    }',
  '    return "download_failed"',
  '  }',
  '  return "no_audio_found"',
  '}',
  'function Find-TaskCandidate($task) {',
  '  $targetFile = TargetPath $task',
  '  if (Test-StableFile $targetFile) { return $targetFile }',
  '  $downloadFile = DownloadPath $task',
  '  if (Test-StableFile $downloadFile) { return $downloadFile }',
  '  $names = Unique-Strings @($task.filename, $task.tempFilename)',
  '  if ($names.Count -eq 0) { return "" }',
  '  $roots = Unique-Strings @((Split-Path -Parent $targetFile), (Split-Path -Parent $downloadFile), (FullPath "idm_downloads"), $baseDir)',
  '  foreach ($root in $roots) {',
  '    if ([string]::IsNullOrWhiteSpace($root) -or !(Test-Path -LiteralPath $root)) { continue }',
  '    foreach ($name in $names) {',
  '      try {',
  '        $candidate = Get-ChildItem -LiteralPath $root -File -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Name -eq $name } | Select-Object -First 1',
  '        if ($null -ne $candidate -and (Test-StableFile $candidate.FullName)) { return $candidate.FullName }',
  '      } catch {',
  '      }',
  '    }',
  '  }',
  '  return ""',
  '}',
  'function Move-CandidateToTarget([string]$candidateFile, [string]$targetFile) {',
  '  if ([string]::IsNullOrWhiteSpace($candidateFile) -or !(Test-Path -LiteralPath $candidateFile)) { return $false }',
  '  if ($candidateFile -eq $targetFile) { return $true }',
  '  $targetDir = Split-Path -Parent $targetFile',
  '  New-Item -ItemType Directory -Force -Path $targetDir | Out-Null',
  '  Move-Item -LiteralPath $candidateFile -Destination $targetFile -Force',
  '  return $true',
  '}',
  'function Resolve-Download($task, [switch]$FinalPass) {',
  '  if (Is-FailedTask $task) {',
  '    Log ("skip failed task: " + (TaskLabel $task 0 0))',
  '    return $true',
  '  }',
  '  $targetFile = TargetPath $task',
  '  $targetDir = Split-Path -Parent $targetFile',
  '  New-Item -ItemType Directory -Force -Path $targetDir | Out-Null',
  '  if (Test-StableFile $targetFile) {',
  '    if ($task.encrypted -and !(Test-Mp4File $targetFile)) {',
  '      Decode-EncryptedFile $task $targetFile',
  '      Log ("decrypted existing target: " + $targetFile)',
  '      return $true',
  '    }',
  '    Log ("already completed: " + $targetFile)',
  '    return $true',
  '  }',
  '  $candidateFile = Find-TaskCandidate $task',
  '  if ([string]::IsNullOrWhiteSpace($candidateFile)) {',
  '    if ($FinalPass) { $script:MissingFiles++; Mark-Failed $task ("missing file -> " + (DownloadPath $task)) }',
  '    return $false',
  '  }',
  '  if (!(Test-StableFile $candidateFile)) {',
  '    if ($FinalPass) { $script:MissingFiles++; Mark-Failed $task ("unstable file -> " + $candidateFile) }',
  '    return $false',
  '  }',
  '  if (-not $task.encrypted) {',
  '    Move-CandidateToTarget $candidateFile $targetFile | Out-Null',
  '    Log ("completed: " + $targetFile)',
  '    return $true',
  '  }',
  '  if (Test-Mp4File $candidateFile) {',
  '    Move-CandidateToTarget $candidateFile $targetFile | Out-Null',
  '    Log ("already decrypted: " + $targetFile)',
  '    return $true',
  '  }',
  '  Decode-EncryptedFile $task $candidateFile',
  '  Move-CandidateToTarget $candidateFile $targetFile | Out-Null',
  '  Log ("decrypted: " + $targetFile)',
  '  return $true',
  '}',
  'function Decode-EncryptedFile($task, [string]$file) {',
  '  $key = [Convert]::FromBase64String($task.decodeStr)',
  '  $fs = [IO.File]::Open($file, [IO.FileMode]::Open, [IO.FileAccess]::ReadWrite, [IO.FileShare]::Read)',
  '  try {',
  '    $buffer = New-Object byte[] $key.Length',
  '    $read = $fs.Read($buffer, 0, $buffer.Length)',
  '    for ($i = 0; $i -lt $read; $i++) { $buffer[$i] = $buffer[$i] -bxor $key[$i] }',
  '    $fs.Seek(0, [IO.SeekOrigin]::Begin) | Out-Null',
  '    $fs.Write($buffer, 0, $read)',
  '  } finally {',
  '    $fs.Close()',
  '  }',
  '}',
  'function Test-Mp4File([string]$file) {',
  '  if (!(Test-Path -LiteralPath $file)) { return $false }',
  '  $fs = [IO.File]::Open($file, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::ReadWrite)',
  '  try {',
  '    if ($fs.Length -lt 12) { return $false }',
  '    $buffer = New-Object byte[] 12',
  '    $read = $fs.Read($buffer, 0, 12)',
  '    return ($read -eq 12 -and $buffer[4] -eq 0x66 -and $buffer[5] -eq 0x74 -and $buffer[6] -eq 0x79 -and $buffer[7] -eq 0x70)',
  '  } finally {',
  '    $fs.Close()',
  '  }',
  '}',
  'function Queue-IdmTask($task, [string]$idman, [int]$index, [int]$total, [string]$reason) {',
  '  $dir = FullPath $task.downloadDirectory',
  '  New-Item -ItemType Directory -Force -Path $dir | Out-Null',
  '  $downloadName = if ([string]::IsNullOrWhiteSpace($task.tempFilename)) { $task.filename } else { $task.tempFilename }',
  '  $targetFile = TargetPath $task',
  '  $downloadFile = Join-Path $dir $downloadName',
  '  if (Test-StableFile $targetFile) { Log ("skip existing file: " + $targetFile); return $true }',
  '  if (Test-StableFile $downloadFile) { Log ("skip existing file: " + $downloadFile); return $true }',
  '  Log ($reason + " " + (TaskLabel $task $index $total) + " -> " + $targetFile)',
  '  & $idman /d $task.url /p $dir /f $downloadName /n /a',
  '  if ($null -ne $LASTEXITCODE -and $LASTEXITCODE -ne 0) { Log ("IDM add returned code " + $LASTEXITCODE + ": " + $task.label) }',
  '  Start-Sleep -Milliseconds 100',
  '  return $true',
  '}',
  'function Recover-Task($task, [string]$idman) {',
  '  if (![string]::IsNullOrWhiteSpace((Find-TaskCandidate $task))) { return $true }',
  '  $key = TaskKey $task',
  '  if (!$script:RecoveryAttempts.ContainsKey($key)) { $script:RecoveryAttempts[$key] = 0 }',
  '  $script:RecoveryAttempts[$key] = [int]$script:RecoveryAttempts[$key] + 1',
  '  $attempt = [int]$script:RecoveryAttempts[$key]',
  '  if ($attempt -le $maxRecoveryAttempts) {',
  '    Log ("direct fallback attempt " + $attempt + ": " + (TaskLabel $task 0 0))',
  '    $ok = Download-DirectFile $task.url (DownloadPath $task) (TaskLabel $task 0 0)',
  '    if ($ok) { return $true }',
  '    if ($attempt -lt $maxRecoveryAttempts) { return $true }',
  '  }',
  '  Mark-Failed $task "recovery attempts exhausted"',
  '  return $false',
  '}',
  '$json = [IO.File]::ReadAllText($TaskFile, [System.Text.Encoding]::UTF8)',
  '$data = $json | ConvertFrom-Json',
  '$idman = $data.idmPath',
  'if ((@($data.downloads)).Count -gt 0) {',
  '  if (!(Test-Path -LiteralPath $idman)) { $idman = "C:\\Program Files\\Internet Download Manager\\IDMan.exe" }',
  '  if (!(Test-Path -LiteralPath $idman)) { throw "IDMan.exe not found" }',
  '}',
  '$downloadRoot = FullPath "idm_downloads"',
  'New-Item -ItemType Directory -Force -Path $downloadRoot | Out-Null',
  'if ((@($data.imageSets)).Count -gt 0) {',
  '  Log ("direct image set downloads: " + (@($data.imageSets)).Count)',
  '  Download-ImageSets @($data.imageSets)',
  '}',
  'if ((@($data.downloads)).Count -gt 0) {',
  '  Log ("add IDM tasks: " + (@($data.downloads)).Count)',
  '  $downloadTasks = @($data.downloads)',
  '  for ($i = 0; $i -lt $downloadTasks.Count; $i++) {',
  '    $task = $downloadTasks[$i]',
  '    Queue-IdmTask $task $idman ($i + 1) $downloadTasks.Count "queue" | Out-Null',
  '  }',
  '  & $idman /s',
  '  if ($null -ne $LASTEXITCODE -and $LASTEXITCODE -ne 0) { Log ("IDM start queue returned code " + $LASTEXITCODE + ", continue anyway") }',
  '  $pending = New-Object System.Collections.Generic.List[object]',
  '  foreach ($task in @($data.downloads)) { $pending.Add($task) | Out-Null }',
  '  $deadline = (Get-Date).AddMinutes(30)',
  '  $idleRounds = 0',
  '  Log ("download rounds start: " + $pending.Count)',
  '  Read-Host "Wait until IDM finishes all downloads, then press Enter to finish"',
  '  while ($pending.Count -gt 0) {',
  '    $next = New-Object System.Collections.Generic.List[object]',
  '    $progress = 0',
  '    foreach ($task in $pending) {',
  '      if (Resolve-Download $task) {',
  '        $progress++',
  '      } else {',
  '        $next.Add($task) | Out-Null',
  '      }',
  '    }',
  '    if ($next.Count -eq 0) { break }',
  '    if ((Get-Date) -ge $deadline) {',
  '      foreach ($task in $next) { Resolve-Download $task -FinalPass | Out-Null }',
  '      break',
  '    }',
  '    if ($progress -gt 0) {',
  '      $idleRounds = 0',
  '      Log ("round complete, remaining: " + $next.Count)',
  '      Log ("pending tasks: " + (FormatTaskList $next 5))',
  '      Start-Sleep -Seconds 1',
  '    } else {',
  '      $idleRounds++',
  '      Log ("still waiting for: " + $next.Count)',
  '      Log ("pending tasks: " + (FormatTaskList $next 5))',
  '      if ($idleRounds -ge $maxIdleRounds) {',
  '        $idleRounds = 0',
  '        $recoveries = 0',
  '        foreach ($task in $next) { if (Recover-Task $task $idman) { $recoveries++ } }',
  '        if ($recoveries -eq 0) {',
  '          foreach ($task in $next) { Resolve-Download $task -FinalPass | Out-Null }',
  '          break',
  '        }',
  '      }',
  '      Start-Sleep -Seconds 5',
  '    }',
  '    $pending = New-Object System.Collections.Generic.List[object]',
  '    foreach ($task in $next) { $pending.Add($task) | Out-Null }',
  '  }',
  '} else {',
  '  Log "no IDM video tasks"',
  '}',
  'if ($script:MissingFiles -gt 0) { Log ("warning missing or unfinished files: " + $script:MissingFiles) }',
  'if ($script:FailedTasks.Count -gt 0) {',
  '  Log "failed task summary:"',
  '  foreach ($failed in $script:FailedTasks) { Log ("  - " + $failed) }',
  '}',
  'Log "done"',
].join('\r\n')
